### PR TITLE
Small improvements to dec_p_derivbound

### PR DESCRIPTION
**Pull request by GeorgeR227**
Removed some intermediate arrays that are not really needed.

### CODE REVIEW

**Comment by GeorgeR227** [comment]
**Before:**
Operator: Boundary
Variant: New Form-1, [0.169584 ms, 0.382176 MB]
Variant: New Form-2, [0.2345205 ms, 0.43472 MB]

Operator: Dual Derivative
Variant: New Dual-Form-0, [0.2308955 ms, 0.434064 MB]
Variant: New Dual-Form-1, [0.179959 ms, 0.38152 MB]

Operator: Exterior Derivative
Variant: New Form-0, [0.218458 ms, 0.361184 MB]
Variant: New Form-1, [0.2857295 ms, 0.444304 MB]

**After:**
Operator: Boundary
Variant: New Form-1, [0.147083 ms, 0.365456 MB]
Variant: New Form-2, [0.247791 ms, 0.365376 MB]

Operator: Dual Derivative
Variant: New Dual-Form-0, [0.250625 ms, 0.36472 MB]
Variant: New Dual-Form-1, [0.158458 ms, 0.3648 MB]

Operator: Exterior Derivative
Variant: New Form-0, [0.194375 ms, 0.344464 MB]
Variant: New Form-1, [0.282 ms, 0.37496 MB]

**Comment by lukem12345** [comment]
Nice. Are there any changes here on the output of `@code_warntype`?

**Comment by GeorgeR227** [comment]
Good catch, the `numeric_sign' was falling into the generic case caused by the issue you linked (attr_types can't be used for inference). I've type-asserted them to be bools and the problem seems to be resolved now.

**Comment by GeorgeR227** [comment]
**Latest:**
Variant: New Form-1, [0.142125 ms, 0.365456 MB]
Variant: New Form-2, [0.2445835 ms, 0.365376 MB]

Operator: Dual Derivative
Variant: New Dual-Form-0, [0.249375 ms, 0.36472 MB]
Variant: New Dual-Form-1, [0.154042 ms, 0.3648 MB]

Operator: Exterior Derivative
Variant: New Form-0, [0.193291 ms, 0.344464 MB]
Variant: New Form-1, [0.28525 ms, 0.37496 MB]

**Comment by lukem12345** [comment]
> Good catch, the `numeric_sign` was falling into the generic case caused by the issue you linked (attr_types can't be used for inference). I've type-asserted them to be bools and the problem seems to be resolved now.

Yeah type-asserting here is a good decision because the `FastDEC` module is allowed to make those sorts of assumptions.

**Review by lukem12345 — APPROVED** [review]

**Pull request merged**
